# Path to your oh-my-bash installation.
export OSH=/home/saad/.oh-my-bash

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-bash is loaded.
OSH_THEME="minimal"
#BASH_THEME="minimal"
# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_OSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $OSH/custom?
# OSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-bash/plugins/*)
# Custom plugins may be added to ~/.oh-my-bash/custom/plugins/
# Example format: plugins=(core rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=( git )

source $OSH/oh-my-bash.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-bash libs,
# plugins, and themes. Aliases can be placed here, though oh-my-bash
# users are encouraged to define aliases within the OSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias bashconfig="mate ~/.bashrc"
# alias ohmybash="mate ~/.oh-my-bash"

alias glog="git log --oneline --decorate --graph --all"
alias news=newsbeuter
alias wifi="sudo systemctl restart network-manager"
alias nogvim="nohup gvim floating enable &"
alias chrome="nohup chromium-browser &"
alias beagle="ssh saad@192.168.7.2"
alias conanclean="rm conanbuildinfo.props conanbuildinfo.txt conan_imports_manifest.txt conaninfo.txt"
alias setPersonalGit="git config user.name \"Saad Rasheed\" && git config user.email \"saarasheed@outlook.com\""
alias freeworkspace="i3-msg workspace "
alias sshextend="ssh-add -t8h -K ~/.ssh/id_rsa"
alias cert="~/.config/polybar/expire.sh"
alias kubectlhelp="printf \"kubectl {get all -n namespace} {get -o yaml -n vault service/vault}"
alias githelp="printf \"Rebasing: git rebase --onto development development yourbranch\nGit Tree: git log --oneline --decorate --graph --all\nSquash: git reset --soft HEAD~N;git commit; git push -f \n Patch: git format-patch COMMIT-ID\nend\"
              "
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
